### ISSUE TITLE
alternative led configuration us

### ISSUE THREAD

**Issue by mon3y78** [edwardtfn/TX-Ultimate-Easy#67]
for us 3 gan:

```yaml
  - platform: partition
    name: "LEDs Button right"
    id: leds_button_right
    internal: true
    segments:
      - id: leds
        from: 6
        to: 7      
      - id: leds
        from: 16
        to: 17
  - platform: partition
    name: "LEDs Button middle"
    id: leds_button_middle
    internal: true
    segments:
      - id: leds
        from: 3
        to: 4     
      - id: leds
        from: 19
        to: 20  
  - platform: partition
    name: "LEDs Button left"
    id: leds_button_left
    internal: true
    segments:
      - id: leds
        from: 0
        to: 1      
      - id: leds
        from: 22  
        to: 23
```
for 4 gang 4:
```yaml 
- platform: partition
    name: "LEDs Button l4"
    id: leds_button_l4
    internal: true
    segments:
      - id: leds
        from: 7
        to: 8
      - id: leds
        from: 15
        to: 16
  - platform: partition
    name: "LEDs Button l3"
    id: leds_button_l3
    internal: true
    segments:
      - id: leds
        from: 5
        to: 6
      - id: leds
        from: 17
        to: 18
  - platform: partition
    name: "LEDs Button l2"
    id: leds_button_l2
    internal: true
    segments:
      - id: leds
        from: 1
        to: 2
      - id: leds
        from: 21
        to: 22
  - platform: partition
    name: "LEDs Button l1"
    id: leds_button_l1
    internal: true
    segments:
      - id: leds
        from: 0
        to: 0
      - id: leds
        from: 23
        to: 24
      - id: leds
        from: 31
        to: 31   
```
![ ddd](https://github.com/user-attachments/assets/3ec6ca30-8da9-4600-8f0a-67f5a871b6b3)
